# Gunakan base image Python 3.10
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependensi sistem
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy file requirements
COPY requirements.txt .

# Install dependencies Python
RUN pip install --no-cache-dir -r requirements.txt

# Copy seluruh project
COPY . .

# Command untuk menjalankan bot
CMD ["python", "main.py"]